Seeing that this script nees to be run sudo, using the current user name is not very useful as it is root. force user name to be specified

diff --git a/setup/configure_samba b/setup/configure_samba
--- a/setup/configure_samba
+++ b/setup/configure_samba
@@ -10,7 +10,8 @@
 
 if [ -z "$1" ]; then
     # No username passed as argument, default to current user
-    user=$(whoami)
+    echo "Error: Must specify username." >&2
+    exit 1
 else
     # Use the provided username
     user=$1
